name: Qwen3.5-397B-A17B (Instruct)
org: Qwen
model_id: Qwen3.5-397B-A17B
model_family: qwen3_5
model_type: open
model_size: 397B
backend: api
model_args:
  api_key_env: QWEN35_API_KEY
  base_url: http://bgpu05.hv.rd.nask.pl:8000/v1
  timeout: 120
  max_retries: 10
  num_threads: 8
generation:
  max_completion_tokens: 64
  temperature: 0.0
  top_p: 1.0
  extra_body:
    chat_template_kwargs:
      enable_thinking: false
